name: Deploy container to Azure Functions App

on:
  push:
    branches: 
      - main

permissions:
  contents: read

env:
  AZURE_FUNCTION_APP_NAME: 'ghactionfuncapp'
  AZURE_RESOURCE_GROUP_NAME: 'GitHubActionsRG'
  LOGIN_SERVER: 'ghsampleacr.azurecr.io'
  REGISTRY: 'ghsampleacr.azurecr.io'
  IMAGE: 'blobeventgridappimg'
  TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Compose Customized Docker Image'
        shell: bash
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: 'Run Azure Functions Container Action'
        uses: Azure/functions-container-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: Azure logout
        run: |
          az logout
